### ISSUE TITLE
Bugged NPC in AV

### ISSUE THREAD

**Issue by Clockwork1987230** [RetroWoW/PTR#1]
Description: Alliance NPC 'Stormpike Mine Layer' 

Current behavior: Alliance NPC is friendly when I was matched on the Horde side in AV

Expected behavior: It should be hostile since I was matched to Horde side

Steps to reproduce the problem: He's walking around AV, clearly bugged from the crossfaction AV

Source:  
![gdsds](https://user-images.githubusercontent.com/33751017/32945017-c0098d7e-cb89-11e7-977d-2c36c2546362.png)

**Comment by MrKelzo** [comment]
Fixed after next restart. Thanks for reporting
