### ISSUE TITLE
Hunter 4 piece T3 bonus not working 

### ISSUE THREAD

**Issue by xiaoxoxo** [RetroWoW/PTR#10]
Description: Buff doesn't work at all
Current behavior: nada buff
Expected behavior: buff should be applied to both pet and character
Steps to reproduce the problem: Equip 4 pieces of hunter T3

You fixed this on old core somewhat, pet didnt get buff still.

Source: https://www.youtube.com/watch?v=4ui6mf3lHSU

**Comment by MrKelzo** [comment]
@robinsch  https://github.com/RetroWoW/RetroWoW/issues/58

**Comment by xiaoxoxo** [comment]
[https://imgur.com/a/VarTW](url)
