### ISSUE TITLE
Poisons have charges - like on older WoW classic versions

### ISSUE THREAD

**Issue by Atany101** [RetroWoW/PTR#17]
**Description**:
Poisons have charges - like on older WoW classic versions
This shouldn't be in WoW 1.12.1 anymore - it was patched out that the poisons always work for 30 minutes. Otherwise they are gone too fast - especially in PvE.

**Steps to reproduce the problem**:

1. Use poisons on weapons while playing rogue
2. The buff icon has charges that diminish

**Source:**
PTR

**Comment by sycvil** [comment]
> This shouldn't be in WoW 1.12.1 anymore

Where is the info from? Patch notes say that it was removed in [2.1.0](http://wowwiki.wikia.com/wiki/Patch_2.1.0):
> Rogue poisons no longer have charges.

But nevertheless I think it would be nice to have charges removed as a server-specific QoL feature.
