### ISSUE TITLE
Some Items that stacked to 200 no longer do

### ISSUE THREAD

**Issue by Phocus26** [RetroWoW/PTR#20]
**Description**:

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Bam27** [comment]
Please include the item IDs of affected items.

**Comment by Phocus26** [comment]
I️ don’t have access to the wide variety of consumables I️ do on live however, noggenfogger stacks to 20 so presumably all items which had their stack sizes increased after nogg, have been reverted.

**Comment by Bam27** [comment]
Most items are stacking to 200, so I need a list of every item that does not which should.

**Comment by exomist** [comment]
Most important one that doesnt stack:
8529 - Noggenfrogger Elixer
