### ISSUE TITLE
Flurry should not be consumed by Windfury procs

### ISSUE THREAD

**Issue by Chireal** [RetroWoW/PTR#21]
Flurry stacks should not be consumed by windfury procs

**Current behavior**: It is consumed

**Expected behavior**: Should not be

**Steps to reproduce the problem**: 

1. Get a critical strike
2. Get a WF proc, while having flurry stacks
3. 

**Source:** https://www.youtube.com/watch?v=ja1j7xWpB3w - 8:54

**Comment by MrKelzo** [comment]
Invalid report, its not getting consumed by WF

**Comment by Chireal** [comment]
Yes, it is consumed. 
Video I just took: https://streamable.com/oi2yo
