### ISSUE TITLE
Corrupted Ashbringer Event is completely broken

### ISSUE THREAD

**Issue by BugsearcherStupidrat** [RetroWoW/PTR#23]
**Description**:
Corrupted Ashbringer Event is completely broken
**Current behavior**: Tell us what happens
Mobs in Scarlet Monastery Cathedral are hostile and work as not intended.
**Expected behavior**: Tell us what should happen instead
They must instantly turn friendly, kneel and say one of scripted phases.
**Steps to reproduce the problem**:

1. Equip Corrupted Ashbringer
2. Enter in Scarlet Monastery Cathedral
3. Look on mobs reaction

**Source:**
![bug3](https://user-images.githubusercontent.com/33780381/32979830-460f875a-cc6d-11e7-9555-72bfa5c69c0d.png)
https://www.youtube.com/watch?v=7S2T6V0LTXA

**Comment by MrKelzo** [comment]
@robinsch https://github.com/RetroWoW/RetroWoW/issues/64
