### ISSUE TITLE
Alterac Valley --> Wing Commander Jeztor bug

### ISSUE THREAD

**Issue by BugsearcherStupidrat** [RetroWoW/PTR#24]
**Description**:
Alterac Valley --> Wing Commander Jeztor bug
**Current behavior**: Tell us what happens
She is broken. She is fighting when dead.
**Expected behavior**: Tell us what should happen instead
She must be inactive and wait until for player's activation
**Steps to reproduce the problem**:

1. Come to this place and attack her.
2. She will attack you.
3. You cannot kill her and she will pursuit you.

Also as bonus Wing Commander Guse is disappearing if you attack her.
**Source:**
![bug4](https://user-images.githubusercontent.com/33780381/32980212-86e4bdda-cc73-11e7-97da-90e03d6cae7e.png)
![5](https://user-images.githubusercontent.com/33780381/32980213-895dfa5e-cc73-11e7-9319-0c80fc28c448.png)

**Comment by MrKelzo** [comment]
http://wowwiki.wikia.com/wiki/Wing_Commander_Guse
