### ISSUE TITLE
Dropping totems uses Eye of the Dead trinket charges

### ISSUE THREAD

**Issue by Brqje** [RetroWoW/PTR#27]
**Description**:
Dropping totems uses Eye of the Dead trinket charges.

**Current behavior**: Tell us what happens
Dropping totems uses Eye of the Dead trinket charges:
https://www.youtube.com/watch?v=c8wEghcZcBE

**Expected behavior**: Tell us what should happen instead
Totems drops should not use Eye of the Dead trinket charges. Only targeted heals should.
(Additional side info: On retail (7.3.2), chain heal uses multiple charges of this trinket:
https://www.youtube.com/watch?v=AhL_sneM8Kg )

**Steps to reproduce the problem**:
1.  Activate Eye of the Dead on a shaman.
2.  Drop a totem.

**Source:**
item 23047

**Comment by MrKelzo** [comment]
Thanks for reporting.
