### ISSUE TITLE
T2 Paladin 8/8 Bonus not scaling with spelldmg any more

### ISSUE THREAD

**Issue by noabyuna** [RetroWoW/PTR#29]
**Description**:
With the new core the 8/8 set bonus does exactly the dmg that it says on the tooltip and doesn't scale with spelldmg any more

**Expected behavior**: Should scale

**Comment by xiaoxoxo** [comment]
https://github.com/elysium-project/server/pull/992 it shouldn't scale.

**Comment by MrKelzo** [comment]
its not scaling, wrong label
