### ISSUE TITLE
Warsong / Silverwing Supply Officers Sells wrong things

### ISSUE THREAD

**Issue by exomist** [RetroWoW/PTR#39]
**Description**:
Warsong / Silverwing Supply Officers Sells wrong things
(Also it would be good to add the AV rep vendors?)
**Current behavior**: They both sell general goods ish items

**Expected behavior**: They should sell reputation items.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Bam27** [comment]
TBD -- Reputation xfaction needs correction first.
