### ISSUE TITLE
Rogue abilities activating Hand of Justice proc

### ISSUE THREAD

**Issue by Krofman** [RetroWoW/PTR#52]
**Description**: Rogue abilities activating Hand of Justice proc

**Current behavior**: So any time when you get critical hit on Hemorhage , Eviscerate ( didnt check Sinister) but could be aswell , Hand of Justice trinket automatically activates after critical , and it should be only 2% chance , its to much OP for rogue to get activated by every critical hit.

**Expected behavior**: Well it shouldnt proc every critical from rogue ability , should be only 2% chance like it is said.
**Steps to reproduce the problem**:

1. Get a critical strike with Hemorhage,Eviscerate
2. Hand of Justice will activate instantly after crit
3. Extra 1 attack every crit

**Source:**

**Comment by Krofman** [comment]
Checked Sinister Strike , same thing happened

**Comment by MrKelzo** [comment]
Fixed after next restart.
