### ISSUE TITLE
Paladin tier 2 8/8 set bonus not scaling at all with spell damage

### ISSUE THREAD

**Issue by sickweirdo** [RetroWoW/PTR#59]
**Description**:
As the title says
**Current behavior**: Tell us what happens
The judgement from the full set bonus of the tier 2 paladin gear doesn't scale at all with spell damage and only does 60 damage
**Expected behavior**: Tell us what should happen instead
It should scale with spell damage
**Steps to reproduce the problem**:

1. equip a pala with full judgement gear
2. cast judgement
3. 

**Source:**
https://www.youtube.com/watch?v=hoOVlOMErIg&t=1s
at 1:10 you can clearly see judgement from the 8/8 set bonus scaling with 223 damage while the normal judgement of command crits for 2257 damage.
at 1:37 you can see judgment hitting for 227 damage

**Comment by MrKelzo** [comment]
Shouldn't scale at all.
