### ISSUE TITLE
Shard of the fallen star doesn't scale with spell damage

### ISSUE THREAD

**Issue by sickweirdo** [RetroWoW/PTR#60]
**Description**:
title
**Current behavior**: Tell us what happens
the trinket doesn't scale with spelldamage
**Expected behavior**: Tell us what should happen instead
it should scale
**Steps to reproduce the problem**:

1. equip shard of the fallen star
2. cast it
3. 

**Source:**
https://www.youtube.com/watch?v=hoOVlOMErIg&t=1s
at 1:10 the meteor does  707 damage while ingame it stays at about 400 with spellpower gear

**Comment by MrKelzo** [comment]
Is intended
