### ISSUE TITLE
wsg and ab tokens stuck in mail

### ISSUE THREAD

**Issue by zyat** [RetroWoW/PTR#68]
**Description**: I logged into ptr with existing character and noticed all the wsg and ab tokens i had in my bags are now stuck in the mail with message saying "problem equipping/storing..."

**Current behavior**: Tell us what happens

**Expected behavior**: Tell us what should happen instead
Don't want to lose tokens when core changes over.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by MrKelzo** [comment]
Thanks for reporting, should be fixed next restart.
