### ISSUE TITLE
LOS Object Correction

### ISSUE THREAD

**Issue by Bam27** [RetroWoW/PTR#7]
Currently objects like trees and other large LoS are acting as if they are not LoS.

On live realm we decided to make these objects act as real LoS; therefore correction to this behavior is in order on PTR.

**Comment by MrKelzo** [comment]
https://github.com/Kelzior/RWCore/commit/36d63acade2da409993e423e2d72715863d05b8c

**Comment by MrKelzo** [comment]
https://github.com/RetroWoW/RetroWoW/issues/117

**Comment by Bam27** [comment]
#81
