### ISSUE TITLE
Paladin healing

### ISSUE THREAD

**Issue by mentos987** [RetroWoW/PTR#73]
I am unsure if the amount healed is the correct one. Tested on a bis pala without the light buff.

**Current behavior**: Rank 6 heals for 980. Rank 1 heals for 650.

**Expected behavior**: On the old core Rank 6 healed for 1200 and Rank 1 for 580

Reasoning: It should be playable and paladins were strong to begin with. But this change seems to further play to the paladin strength, which is to downrank for infinite casting. Things will be less interesting when mana managing isn't as important.

**Comment by MrKelzo** [comment]
FoL heals are corrected @PTR. It heals more on live atm (which is wrong)

**Comment by mentos987** [comment]
rank 1 FoL still heals a lot.

With bis gear and Light buff:
R1 heals for 768 and cost 35mana
R6 heals for 1180 and cost 140mana

It might be correct but it should be less fun to play with. Since you won't ever need to do anything but spam rank 1.

**Comment by mentos987** [comment]
Both ranks gain just as much +heals per healingpower. Which makes rank 6 more and more pointless the more healingpower you have
