### ISSUE TITLE
mounts and noggenfogger

### ISSUE THREAD

**Issue by mcgankinston** [RetroWoW/PTR#75]
**Description**:
ik its not a bug but it would be nice to be able to mount with noggenfogger(skeleton) l
**Current behavior**: Tell us what happens
can't mount with skeleton form
**Expected behavior**: Tell us what should happen instead
blizzlike yet doesit have to be?
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by MrKelzo** [comment]
Thanks for your suggestion but we want to keep it "blizzlike" :)
