### ISSUE TITLE
LOS issues with Guards at GYS

### ISSUE THREAD

**Issue by Heckz** [RetroWoW/PTR#81]
**Description**:
stormpike bowman attack you when you are LOS 
**Current behavior**: Tell us what happens
Hid behind trees with aggro and they still attacked me threw them. But if i went to a bridge pillar then it seemed to have them stop attacking.
**Expected behavior**: Tell us what should happen instead
they should stop attacking when they cant see you. Example when behind a tree

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by Heckz** [comment]
Also tested that you can Attack Player vs player through a tree assuming its the same problem as with the guards but just wanted to let you know

**Comment by MrKelzo** [comment]
This is blizzlike and not a bug. We will discuss it with the team and change it back to our custom one if need.

**Comment by MrKelzo** [comment]
Update: Custom LoS implemented. Should be like on live now.
