### ISSUE TITLE
Paladins can cap Snowfall Gy while bubbled

### ISSUE THREAD

**Issue by Piecars** [RetroWoW/PTR#82]
**Description**: 

[Alterac Valley on the PTR]

As a paladin it is possible to run to the Snowfall GY flag, blessing of protection yourself and click the flag, done fast enough you can cap the GY

**Current behavior**: 

flags can be captured with blessing of protection up
**Expected behavior**: 

they shouldnt, just like you cant cap with divine shield up
 divine shield works as intended

**Steps to reproduce the problem**:

1. roll a paladin
2. Run to the graveyard flag
3. bubble and click the flag
4. laugh at elite mobs not stopping you

**Source:**
me, Piecar
![wowscrnshot_050918_231734](https://user-images.githubusercontent.com/39148006/39853735-20c9e41c-53e1-11e8-8c12-2ac2f80bca1d.jpg)

**Comment by MrKelzo** [comment]
This counts only for spells that make you 100% immune to damage, BoP is only immune to physical attacks.
