### ISSUE TITLE
Target Dummies

### ISSUE THREAD

**Issue by Pogkopi** [RetroWoW/PTR#87]
**Description**:It's often annoying when u want to get fast to some point on mount, but u can't because of this bug

**Current behavior**: If someone hitting dummy after i did i can't get out from combat

**Expected behavior**: I should get out of combat after i finished hitting

**Steps to reproduce the problem**: Unfortunately I don't know...

**Comment by MrKelzo** [comment]
You won't get out of combat until the dummy is out of combat.

**Comment by Pogkopi** [comment]
Please reset the data with releasing new core! It will be more fun to play
again and feel all the advantages of vanilla, also please make alt looting
impossible!

Thanks, Retro-wow player!

2018-05-13 17:17 GMT+03:00 Kelzo <notifications@github.com>:
