### ISSUE TITLE
Scare beast: Hunter ability 

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/PTR#88]
Current behavior: A hunter can't use the spell Scare beast (https://classicdb.ch/?spell=14446)
on a hunter's pet. He can use it on a druid in bear/cat; so this spell is partially bugged. 
Only need to make hunter's pet vulnerable to that spell now.

Expected behavior: The spell Scare beast should be possible to apply to another hunter's pet

Steps to reproduce the problem: Try to use Scare beast on a hunter's pet and see that you cannot do it

Source (proofs for this behavior):

**Comment by MrKelzo** [comment]
https://github.com/RetroWoW/PTR/blob/master/README.md

**Comment by MrKelzo** [comment]
![image](https://user-images.githubusercontent.com/25086832/39967914-5a9127a6-56c4-11e8-819f-fa2ab613d5be.png)
