### ISSUE TITLE
Hunter: flare in stealth is a bug

### ISSUE THREAD

**Issue by Sunqtt** [RetroWoW/PTR#89]
Current behavior: You have as a rogue a short duration of time when you are invisible to the ennemy while vanishing through their flare; allowing you to, for instance, have the time to cheap shot the hunter.

Expected behavior: Vanishing through a vanish will not cancel the flare effect, and the rogue should stay visible at all cost.

Steps to reproduce the problem:
Use vanish in a flare 
https://classicdb.ch/?spell=1543

Source: 

At 3:40 and 23:45. Both of these rogue keep flare as a debuff and are always therefore, visible. So not able to use any ability requiring stealth

https://www.youtube.com/watch?v=dPtSiKS5lJw&t=0s&index=4&list=PLCB0FB4A32F0F4FC4

**Comment by MrKelzo** [comment]
Source?
