### ISSUE TITLE
Combat duration

### ISSUE THREAD

**Issue by Uggly** [RetroWoW/PTR#9]
**Description**: Seems like combat last longer than it should (like 6sec instead of 5.5sec)

**Current behavior**:  For instance, rogues can't stealth after gouge (improved one) people can CC/hit you for little lapse of time

**Expected behavior**: You should be able to restealth just after gouge

**Comment by xiaoxoxo** [comment]
source

**Comment by Bam27** [comment]
Please provide video source circa 1.12 for confirmation.

**Comment by Uggly** [comment]
Ok actually seems like Im wrong according to http://vanilla-wow.wikia.com/wiki/Combat
But I always though combat lasted for less than 6sec
