### ISSUE TITLE
Food & Shards

### ISSUE THREAD

**Issue by Pogkopi** [RetroWoW/PTR#93]
**Description**:Small amount of food/shards

**Current behavior**: Vendor selling only 1 soul shard , adn only 1 piece of fruitcake
**Expected behavior**: Increase it please to 5 or 10 atleast cuz it takes too much time to buy food

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by mentos987** [comment]
Shift-click and type in 200 and you should get 200 instead of only one.
