### ISSUE TITLE
Warlock Abilities

### ISSUE THREAD

**Issue by Pogkopi** [RetroWoW/PTR#94]
**Description**:Fel Domination ability is not working

**Current behavior**: When im poping it it not decreasing casting time by 5.5 sec, its doing nothing
**Expected behavior**: Casting time of Succubus while im under the influence of this Ability shoud be 0.5 sec

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by MrKelzo** [comment]
Works fine;

![image](https://user-images.githubusercontent.com/25086832/40946962-7ec85c7c-6860-11e8-9dba-68c6313a4563.png)
