### ISSUE TITLE
.st non exsistant  and .rep not working 

### ISSUE THREAD

**Issue by irishpuffin** [RetroWoW/PTR#95]
Description: not sure if this is intended but didn't see it anywhere. the .start function doesn't exist. also .repair is there but .rep is not (in case you were wondering. If you are intending to take out .start, can I make a suggestion that you don't due to the fact that Hyjal is a nuetral mall and you cant really take a wind rider there. so your kinda stranded if you get ported to Brd lets say when you died in MC.

Current behavior: when i use the command i just reappear in same spot

Expected behavior: bring me back to hyjal

Steps to reproduce the problem:

    type .st

Source:
PTR

Also, i was testing different instances and wasnt allowed to enter anymore instances said " you have entered to many instances recently" may want to change that for people testing out the raids on PTR.

**Comment by MrKelzo** [comment]
.st is blizzlike now
and to repair, you have to use .repair and not .rep
