### ISSUE TITLE
Not able to mount in shadowform

### ISSUE THREAD

**Issue by zyat** [RetroWoW/PTR#97]
**Description**:  At first I was able to mount in shadowform no problem.  And I noticed others not having this issue.  But I after I died and resed in AV I couldn't mount in shadowform and even after dropping it I couldn't mount.

**Current behavior**: 
Couldn't mount.  See screenshot https://imgur.com/a/V8XUl7X

**Expected behavior**: Always should be able to mount in or out of shadowform

**Steps to reproduce the problem**: Not sure, could be related to dying in AV or just timing

**Comment by zyat** [comment]
I just had it happen in WSG without dying

**Comment by MrKelzo** [comment]
Patch 3.0.8 (2009-01-20): You can now shift into Shadowform while mounted or sitting.
+ https://github.com/RetroWoW/PTR/issues/69
