### ISSUE TITLE
Shadow priest damage

### ISSUE THREAD

**Issue by zyat** [RetroWoW/PTR#98]
**Description**: Not sure if this is bug in current server or PTR but I noticed difference in shadow priest damage.  Don't know which scaling is correct.

**Current behavior**: Tested spells with same gear and buffs
spell, live, ptr
mindflay, 382, 349
swp, 393, 367
mind blast, ~1040, ~1090
So DOTs hitting for less, direct damage hitting for more.

**Expected behavior**: Not sure which is correct.

**Comment by MrKelzo** [comment]
PTR has corrected calculations.
